# Generated by Django 4.0.4 on 2022-04-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='visibility',
        ),
        migrations.AddField(
            model_name='article',
            name='for_subscribers',
            field=models.BooleanField(default=False),
        ),
    ]
