# Generated by Django 4.0.4 on 2022-04-17 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_journaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
